version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./db-init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  backend:
    image: node:8
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    command: "/bin/bash -c 'cd /backend && npm install -g nodemon && npm install && node knexfile.js && npm run knex migrate:latest && npm run knex seed:run && npm start'"
    links:
      - database:db
  
