version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  backend:
    image: node:8
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    command: "/bin/bash -c 'cd /backend && npm install && npm start'"
    links:
      - database:db
  